version: "3"

services:
  node-server:
    build:
      context: ./address-book-server
      dockerfile: node.dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./address-book-server:/node-server
      - /node-server/node_modules
    networks:
      - nodeapp-network

  angular-server:
    build:
      context: ./address-book-client
      dockerfile: client.dockerfile
    ports:
      - "4201:4201"
    volumes:
      - ./address-book-client:/ng-app
      - /ng-app/node_modules
    working_dir: /ng-app
    networks:
      - nodeapp-network
    links:
      - node-server


networks:
  nodeapp-network:
    driver: bridge
